sdgtt/jenkins-shared-library

src/sdg/Gauntlet.groovy
vars/getGauntlet.groovy

Features and fixes included in this PR:
1.  fix: Add 'board_name' argument  to set-local-nic-ip to allow execution on agents with multiple device config
2.  feature: Add LibAD9361 test  to stage library
3. fix: add 'branch' parameter in dl.bootfiles to set linux branch instead of default 'master'

feat: Add LibAD9361 tests to stage library and fix some argument passing issues

---

src/sdg/Gauntlet.groovy
vars/getGauntlet.groovy

This PR consist of several features and fixes:
1. Add more supported devices to 'LibAD9361Tests' stage
2. Add initial codes for elastic search logging
3. Parametrize source repo and branches  for easy reconfiguration
4. Ignore lines with non alphanumeric characters in parsing return string of 'nebula' method
5.  Delete old source repos when updating agents.

Merge adgt-test-harness modifications

---

src/sdg/Gauntlet.groovy
vars/getGauntlet.groovy

This merge will modify jenkins-shared-library to support the daily builds feature support of nebula.

add 'branches' support

---

src/sdg/Gauntlet.groovy

Signed-off-by: Paller <KimChesed.Paller@analog.com>
This PR adds the --firmware option to nebula dl.bootfiles command for pluto.

fix: add --firmware option to download firmware for pluto

---

src/sdg/FailSafeWrapper.groovy
src/sdg/Gauntlet.groovy

Various commits that lets support for board recovery

Recover stage

---

src/sdg/Gauntlet.groovy

Some commits related to  support telemetry logging

Telemetry logging

---

src/sdg/Gauntlet.groovy

This is to sync changes made in nebula/master to the jenkins shared library.

Change dmesg err log filename

---

src/sdg/Gauntlet.groovy

Added reading git sha properties from yaml file in SendResults stage.

Added reading git sha properties from yaml file

---

src/sdg/Gauntlet.groovy

Signed-off-by: Travis F. Collins <travis.collins@analog.com>

Add serial URI support

---

src/sdg/FailSafeWrapper.groovy
src/sdg/Gauntlet.groovy

A number of features and fixes:
1. Support for Recovery Stage
2. Populate telemetry fields 
3. Improved error reporting

Features and fixes

---

src/sdg/Gauntlet.groovy

Retry steps that requires downloading from internet

Add retry on steps requiring downloading from internet

---

src/sdg/Gauntlet.groovy

This PR adds the following feature and chore tasks:
1. add adi_diagnostic report support
2. cleanup Linux Test stage
3. archive missing iio devices

Adi diagnostic report support

---

src/sdg/FailSafeWrapper.groovy
src/sdg/Gauntlet.groovy

Manually install libiio python bindings after libiio installation

Fix iio not defined

---

src/sdg/Gauntlet.groovy

- Archive xml result
- Search for any *Results.xml file which can either be HWTestResults or LTETestResults

MATLAB stage updates

---

src/sdg/Gauntlet.groovy
vars/getGauntEnv.groovy

This PR is for the addition of no- OS stage support to jenkins stage library.

No OS stage

---

Jenkinsfile-template

Add Jenkinsfile template for reference

---

src/sdg/Gauntlet.groovy

Update BOOT Files stage fails for Pluto when docker host mode is false, which is required when using MATLAB.
This change skips the stage for Pluto when MATLAB is included in docker_args. 
Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>

Skip pluto firmware update for MATLAB pipelines

---

src/sdg/Gauntlet.groovy

This custom stage will generate and save context files for use in [emulation](https://pytest-libiio.readthedocs.io/en/latest/emulation/)
To do (some other PR):
- Save to elasticsearch
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

Add custom stage for IIO context capturing

---

src/sdg/FailSafeWrapper.groovy
src/sdg/Gauntlet.groovy
vars/getGauntEnv.groovy

PR adds flags and logic to download BOOT.BINs from MATLAB generated designs

Add MATLAB bootbin testing support

---

doc/source/index.rst
doc/source/vagrant.rst
vars/check_for_box.groovy
vars/check_for_snapshot.groovy
vars/check_node.groovy
vars/get_vagrant_vm_id.groovy
vars/run_closure.groovy
vars/setup_jenkins_agent_on_vagrant_vm.groovy
vars/setup_vagrant_box.groovy

In this PR are two commits. 
The first will add some scripts for Jenkins Shared Libray in Vagrant project.
The second will add documentation for each scrippt.
Signed-off-by: Chis Raluca [raluca.chis@analog.com](mailto:raluca.chis@analog.com)

Add vagrant scripts

---

src/sdg/Gauntlet.groovy

Add guard to make sure lockname is none empty string

Update Gauntlet.groovy: extractLockName

---

src/sdg/Gauntlet.groovy

When url-template is not available or set to NA, downloading fails. Updated the command to remove url template if none is passed.
Also added update on checking required hardware, there was instance that adrv9009zu11eg was still added even though it was not listed as required hardware

fix downloader nebula command

---

src/sdg/Gauntlet.groovy

Added fixes:
1. Required hardware mapping logic

Hdl ci support

---

src/sdg/Gauntlet.groovy

This PR updates the implementation of scm checkout of pyadi-iio and MATLAB.

Multibranch update

---

src/sdg/Gauntlet.groovy
vars/getGauntEnv.groovy

This PR includes feature to log journal when lock is acquired on a board. If board is not active it will stop succeeding stages.
Also added changes on the following:
1. removed setting up dependencies (installing) on agents (this will require us to update our libraries on the agent itself manually or another way to update it)
2. updated checking of required dependencies to be updated in docker container. Added main as default branch also

log Journal for resource locking

---

src/sdg/Gauntlet.groovy

Clean workspace first before running any build. This has not yet been tested when using multibranch pipelines.

Fix cleanup

---

src/sdg/Gauntlet.groovy

multibranch PR fail checkout unless refspec is added in the checkout config
correct refspec pattern for PRs: +refs/pull/<pr_number>/head:refs/remotes/origin/PR-<pr_number>
current (issue): +refs/heads/*:refs/remotes/origin/*
Tested on these pipelines
[MATLAB multibranch pipeline, branch](gateway.englab/jenkins/blue/organizations/jenkins/MATLAB_Toolboxes%2FHigh_Speed_Converter_Toolbox_Hardware_Tests/detail/harness-updates/8/pipeline/221) 
[MATLAB multibranch pipeline, pr](gateway.englab/jenkins/blue/organizations/jenkins/MATLAB_Toolboxes%2FHigh_Speed_Converter_Toolbox_Hardware_Tests/detail/PR-164/16/pipeline/266)
[pyadi multibranch pipeline, branch](gateway.englab/jenkins/blue/organizations/jenkins/cct%2Ftest_pyadi_iio/detail/main/89/pipeline)
[pyadi multibranch pipeline, …

Fix scm checkout for PRs on multibranch pipelines

---

src/sdg/Gauntlet.groovy

Fix repo clone for multibranch but not current repo CI

---

src/sdg/Gauntlet.groovy
src/sdg/IStepExecutor.groovy
src/sdg/StepExecutor.groovy
src/sdg/stages/UpdateBOOTFiles.groovy
src/sdg/stages/noOSTest.groovy
test/sdg/stages/TestnoOSTest.groovy

This PR includes refactoring no-os stage to new structure.

Refactor noos

---

src/sdg/Gauntlet.groovy
src/sdg/IStepExecutor.groovy
src/sdg/StepExecutor.groovy
src/sdg/stages/CaptureIIOContext.groovy
src/sdg/stages/PowerCycleBoard.groovy
src/sdg/stages/SendResults.groovy
test/sdg/stages/TestCaptureIIOContext.groovy
test/sdg/stages/TestPowerCycleBoard.groovy
test/sdg/stages/TestSendResults.groovy

Refactored CaptureIIOContext, PowerCycleBoard, SendResults. Also added tests.

Refactor utilities

---

src/sdg/Gauntlet.groovy

added as space command line argument " --board-name "in the disable command for netbox disable

added space in command line arguement --board-name for netbox disable

---

.github/workflows/build.yml
src/sdg/Gauntlet.groovy
src/sdg/IStepExecutor.groovy
src/sdg/StepExecutor.groovy
src/sdg/stages/KuiperCheck.groovy
src/sdg/stages/LibAD9361Tests.groovy
src/sdg/stages/LinuxTests.groovy
src/sdg/stages/MATLABTests.groovy
src/sdg/stages/PyADITests.groovy
src/sdg/stages/RecoverBoard.groovy
src/sdg/stages/UpdateBOOTFiles.groovy
test/sdg/stages/TestKuiperCheck.groovy
test/sdg/stages/TestLibAD9361Tests.groovy
test/sdg/stages/TestLinuxTests.groovy
test/sdg/stages/TestMATLABTests.groovy
test/sdg/stages/TestPyADITests.groovy
test/sdg/stages/TestRecoverBoard.groovy
test/sdg/stages/TestUpdateBOOTFiles.groovy
vars/getGauntEnv.groovy

Refactored following stages:
- PyADITests
- LibAD9361Tests
- MATLABTests
- KuiperCheck
Also fixed some tests on following stages:
- LinuxTests
- RecoveredBoard
- UpdateBootFiles

Refactor stages
