sdgtt/jenkins-shared-library

- src/sdg/Gauntlet.groovy
This feature will allow updating of tools on agents separately by calling  'update_agents()' in the pipeline job. In this function, it will clone and install the tools on all the agents available, the cloned repository will be copied to the agent's local directory in order to be reused when docker mode is enabled.  
When docker mode is enabled, setting up the same tools is also required. This feature will allow using the stored local copy of the repository in order to install the tools, removing the downloading of the repository in every container that is created.
> Separate updating of tools on agent

- doc/source/pipeline.rst
- src/sdg/FailSafeWrapper.groovy
- src/sdg/Gauntlet.groovy
- src/sdg/NominalException.groovy
This feature will allow a custom execution type of a stage when added using the 'Gauntlet.add_stage' method.
This ensures a non-requisite stage to fail gracefully and proceed to next stage.
For this, 2 currently supported options to the 'add_stage' method is added as parameters.
1. "stopWhenFail"(Default) 
- stops whole pipeline execution at error
- set build status to 'FAILURE'
2. "continueWhenFail" 
- stops current stage execution at error but proceeds to next.
- set build status to 'UNSTABLE'
Sample Usage:
```
harness.add_stage(harness.stage_library("UpdateBOOTFiles")) //Default
harness.add_stage(harness.stage_library("LinuxTests"),"stopWhenFail")
harness.add_stage(harness.stage_library("PyADITests"),"continueWhenFail")
harness.add_stage(harness.stage_library('LibAD9361Tests'),"continue …
```
> Feat: Add failsafe feature in execution of stages

- doc/source/pipeline.rst
- src/sdg/FailSafeWrapper.groovy
- src/sdg/Gauntlet.groovy
- src/sdg/NominalException.groovy
This feature will allow a custom execution type of a stage when added using the 'Gauntlet.add_stage' method.
This ensures a non-requisite stage to fail gracefully and proceed to next stage.
For this, 2 currently supported options to the 'add_stage' method is added as parameters.
1. "stopWhenFail"(Default) 
- stops whole pipeline execution at error
- set build status to 'FAILURE'
2. "continueWhenFail" 
- stops current stage execution at error but proceeds to next.
- set build status to 'UNSTABLE'
Sample Usage:
```
harness.add_stage(harness.stage_library("UpdateBOOTFiles")) //Default
harness.add_stage(harness.stage_library("LinuxTests"),"stopWhenFail")
harness.add_stage(harness.stage_library("PyADITests"),"continueWhenFail")
harness.add_stage(harness.stage_library('LibAD9361Tests'),"continue …
```
> Feat: Gauntlet: Add failsafe feature in execution of stages

- src/sdg/Gauntlet.groovy
This modification will ignore lines with non-alphanumeric characters in parsing of 'nebula' method output.
Ex. use case (ignores the following icon which is currently returned by nebula command)
```
_   __     __          __               ____   ___
/ | / /__  / /_  __  __/ /___ _   _   __/ __ \ <  /
/  |/ / _ \/ __ \/ / / / / __ `/  | | / / / / / / / 
/ /|  /  __/ /_/ / /_/ / / /_/ /   | |/ / /_/ / / /  
/_/ |_/\___/_.___/\__,_/_/\__,_/    |___/\____(_)_/ 
```
> Gauntlet: ignore lines with non alphanumeric characters in method 'nebula'

- src/sdg/Gauntlet.groovy
- vars/getGauntlet.groovy
This PR contains the following modifcations/features:
1. Add support for the daily build feature.
2.  Add error handling for gathering of dmesg logs (LinuxTest stage)
3. Add --network host docker argument to expose host network to docker containers. This enables virtual NIC (e.g pluto) to be discovered by the tests running on that containers.
> Add suport for daily build feature

- src/sdg/Gauntlet.groovy
This change removes the step to install telemetry's development dependencies that are not needed.
This should change the telemetry install time from 40 seconds to 2 seconds.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
> Telemetry remove dev dependencies

- src/sdg/Gauntlet.groovy
If docker is in host mode it will break forced mac addresses which are required for MATLAB and Vivado configs.
PR makes it configurable but does not change default behavior.
Please squash merge.
> Make docker host mode configureable

- src/sdg/Gauntlet.groovy
pyadi has already added pytest-html support and this commit adds the
necessary flags the collects the generated HTML with the HTML-Publisher
plugin
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
> Add html report logging for pyadi tests

- src/sdg/Gauntlet.groovy
This added support to handle adrv9002 variants. Board names with -v<variant> at the end of their board name are parsed, getting the <variant> to be passed as a marker to pyadi-iio test. 
This also adds a feature that ensures a resource having different variants will only be accessed and used one variant at a time, this is by using the lock feature.
This feature is dependent on nebula config and nebula.
> Adrv9002 variants support

- src/sdg/Gauntlet.groovy
Add field to identify how and which job triggered the job. This info is included on telemetry data.
> send telemetry info on what triggered the build

- src/sdg/Gauntlet.groovy
Additional env variables with default values:
- matlab_release: 'R2021a',
- matlab_repo: 'https://github.com/analogdevicesinc/TransceiverToolbox.git',
- matlab_branch: 'master',
- matlab_commands: [],
MATLAB commands are written using typical MATLAB syntax.
`harness.set_matlab_commands(["ad=adi.utils.libad9361",
"ad.download_libad9361()",
"addpath(genpath('test'))",
"pyenv('Version','/usr/bin/python3')",
"runHWTests(getenv('board'))"])`
Multibranch pipelines **do not use** MATLAB repo and branch because the checkout process is done using checkout scm while non-multibranch pipelines manually clone the specified branch of the specified repo. checkout scm fails for non-multibranch pipelines.
isMultiBranchPipeline() checks if the job is a multibranch pipeline using checkout scm. …
> Add MATLAB stage

- src/sdg/Gauntlet.groovy
White spaces in Jenkins job name causes field mismatch in telemetry commands. The job name is passed in quotation marks to fix the issue.
MATLAB test failures, errors, skipped, and total tests are taken from the HWTestResults.xml file which is parsed similar to pytest results. The parsing was rewritten as a function and is called for both MATLAB and pytests.
Added MATLAB fields for boot_logs index requires https://github.com/sdgtt/telemetry/pull/16.
Signed-off-by: Julia Pineda <Julia.Pineda@analog.com>
> Fix SendLogsToElastic stage call from MATLAB pipelines

- src/sdg/Gauntlet.groovy
Failing MATLAB tests will raise nominal exception to proceed with next stages.
Updated xml file generated to reflect changes inside toolbox repos.
> MATLAB-elastic updates

- src/sdg/Gauntlet.groovy
Add serial backend when installing libiio.
> Add serial backend in libiio install

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
**logJira(jiraArgs)** method first checks if an issue with summary in the form "[carrier-daughter] Stage failure message" exists in the project.  Carrier and daughter board names are read from nebula-config, requiring these changes https://github.com/sdgtt/nebula-config/pull/2
A comment is added if the issue exists. Otherwise, an issue is created. 
**jiraArgs** is a map for Jira issue fields. The only hard requirement is the issue summary. Default values are assigned to relevant  fields which are overwritten when listed in jiraArgs. If an issue exists and **description** is included in jiraArgs, the description appears in the added comment.
The **attachment** key in jiraArgs should have a list value. Attachments are uploaded for all stages other than the libad9361, work in progress. 
The …
> Integrate Jira issue creation/update

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
This PR implements:
1. Allow custom template for nebula-config generation
2. Point to apt-ng  cache proxy server
> Allow custom template for nebula-config generation

- src/sdg/Gauntlet.groovy
This is a fix to check_markers method. Check for valid markers for pytest and ignore other -v<variants>. Other -v<variants> are used for resource locking.
> fix: check for valid markers

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
I created this to support the changes in telemetry https://github.com/sdgtt/telemetry/pull/34/files
I added a credentials_id variable that should be a Jenkins username-password credential id stored in Jenkins with read access. The default value is an empty string. When the variable is set in the pipeline config, --jenkins-user and --jenkins-pass are appended to the telemetry command string. The username is exposed in the log but the password is hidden.
> Add Jenkins credentials in Log Artifacts stage

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
This PR addresses the hang issue on Pluto hw tests. I added a variable matlab_timeout that accepts timeout -s KILL duration as a string. The default value is '10m' for 10 minutes. Toolboxes hw tests do not exceed five minutes on average. The only pipeline where MATLAB stage takes longer to finish is the weekly LTE tests. A setter method is available and should be added for that pipeline.
I tested this using an infinite loop and MATLAB terminated after five minutes.
http://gateway.englab/jenkins/job/Misc/job/Trx_JenkinsfileHW/84/console
> MATLAB: Add timeout when running MATLAB

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
This PR includes changes that updates setting up the docker container and how nebula, libiio, and telemetry are updated if needed.
1. The default docker image used is now set to test-harness-ci:latest. This image already has pre-installed nebula, libiio, and telemetry, all are based from master branch.
2. Reinstalling the libraries ( nebula, libiio, and telemetry ) upon setup is also possible by still using the set_env method to set the repo link and repo branch. A function to check if there is difference of the newly set and default is placed to see if there is a need to update the libraries: _check_update_container_lib_
3. If needed to update the libraries ( nebula, libiio, and telemetry ) upon setup base on master, it is possible to use the  _update_container_lib_ and set it to true. …
> Update setup docker

- src/sdg/Gauntlet.groovy
This PR is to address the issues encountered recently regarding open screen sessions while pipeline jobs are running.
The change is to close detached screen sessions during updating the agents.
> Screen issue

- src/sdg/Gauntlet.groovy
In pyadi-iio test stage, I added a feature to enable checkout scm. It is still possible to pass pyadi-iio branch and repo if the pipeline is not multibranch.
> pyadi-iio: add checkout scm

- src/sdg/Gauntlet.groovy
- vars/getDockerConfig.groovy
- vars/getGauntEnv.groovy
The MATLAB Tests stage requires a container to have the same MAC address as the machine-specific license file. The MAC address is automatically set when MATLAB is added as a requirement in the pipeline.  This also requires the docker host mode to be set to false.
Using a network license removes the need to set the MAC address in the container and docker host mode can now be set to true. I added matlab_license variable that can be set to either 'network' or 'machine' to support this change. The default value is still 'machine'.
These changes will not require updating the JenkinsfileHW in the toolbox repos but I plan to update them to:
- set the license to 'network'
- set docker host mode to true
- set lock agent to false - This lock was implemented as a workaround to MATLAB stage failures …
> Support MATLAB network license

- src/sdg/Gauntlet.groovy
This PR includes installation of libad9361-iio python bindings in order for fmcomms5 chip b tests to run.
> Pyaditest stage update

- src/sdg/Gauntlet.groovy
This is a fix to generating nebula config when adding variant or children is false.
> fix config generation when no variant or no children

- Jenkinsfile-template
- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
This should reduce Gauntlet bytecode size enough to make the adgt-test-harness branch usable.
> Remove deprecated logJira method

- src/sdg/Gauntlet.groovy
- vars/getGauntEnv.groovy
These changes enable mounting workspace specific nebula-config files in the docker containers instead of mounting the /etc/default/nebula file found in the agent.
These changes are made to support DUT locking such that several pipelines can run simultaneously - generating their own updated nebula-config.
> Use nebula-config from pipeline workspace

- src/sdg/Gauntlet.groovy
This should fix the license issues on the MATLAB pipelines by using a user other than root. The non-root "user" requires write permission to the workspace. The necessary docker image changes are already merged. I tested these changes using the [Transceiver Toolbox](http://gateway.englab/jenkins/job/MATLAB_Toolboxes/job/Transceiver_Toolbox_Hardware_Tests/job/master/133/) which uses nucs 1 and 2, as well as the [Precision Toolbox ](http://gateway.englab/jenkins/job/MATLAB_Toolboxes/job/Precision_Toolbox/job/main/54/)which uses nuc4.
> Run MATLAB as non-root user

- src/sdg/Gauntlet.groovy
Updated installation method for pytest-libiio to use "pip3 install . " instead of setup.py.
> pytest libiio fix
